version: '3'
services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: /bin/sh -c "cd react_app && yarn start"
    ports:
      - '8000:3000'
